version: "3"

networks:
  yue3000-mall:
    driver: bridge

services:
  mall-redis:
    container_name: mall-redis
    image: redis
    ports:
      - "6379"
    networks:
      - yue3000-mall
  mall-api:
    container_name: mall-api
    restart: always
    build: ../app
    volumes:
      - ../app/api:/api/api
      # - ../build:/api/build
      - ../app/config:/api/config
      - ../app/hooks:/api/hooks
      - ../app/plugins:/api/plugins
    command:  yarn start
    ports:
      - "1337:1337"
    networks:
      - yue3000-mall
  mall-nginx:
    container_name: mall-nginx
    build:
      context: ../
      dockerfile: docker/nginx/dockerfile
    depends_on:
      - "mall-api"
    volumes:
      - ../build:/build
      - ./nginx/config:/etc/nginx/conf.d
      - ./nginx/certificate:/certificate
      - ./log/nginx/logs:/logs
    ports:
      - "80:80"
      - "443:443"
    networks:
      - yue3000-mall
